eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: application-customer
          uri: http://customer-service:8081/
          predicates:
            - Path=/api/customers/**
        - id: application-account
          uri: http://account-service:8082/
          predicates:
            - Path=/api/accounts/**
        - id: application-transaction
          uri: http://transaction-service:8083/
          predicates:
            - Path=/api/transactions/**
